### PR TITLE
Changed !pip to %pip

### LINKED ISSUE #962: [BUG] Using %pip instead of !pip
### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### Feathr version

0.9.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 20.0)**:
- **Python version**: 3.9.12
- **Spark version, if reporting runtime issue**:

### Describe the problem

When running `!pip install "feathr[notebook]"`, feathr is installed to the local environment. If venv is used to create the virtual environment, a new kernel needs to be created to correctly import feathr. So, my suggestion is to install feathr with `%pip install "feathr[notebook]"` to install the library to the Jupyter Notebook instance.

### Tracking information

_No response_

### Code to reproduce bug

_No response_

### What component(s) does this bug affect?

- [X] `Python Client`: This is the client users use to interact with most of our API. Mostly written in Python.
- [ ] `Computation Engine`: The computation engine that execute the actual feature join and generation work. Mostly in Scala and Spark.
- [ ] `Feature Registry API`: The frontend API layer supports SQL, Purview(Atlas) as storage. The API layer is in Python(FAST API)
- [ ] `Feature Registry Web UI`: The Web UI for feature registry. Written in React

### PR DESCRIPTION
**Pull request by ahlag**
## Description

Resolves #962 

## How was this PR tested?

Change
```sh
!pip install "feathr[notebook]"
```
to 
```sh
%pip install "feathr[notebook]"
```

## Does this PR introduce any user-facing changes?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Make sure to clarify your proposed changes.

### CODE REVIEW

**Comment by loomlike** [comment]
Thank you for the changes. Can you also update the same across other notebooks?

**Comment by ahlag** [comment]
@loomlike 
Yeah sure. Np!

**Comment by ahlag** [comment]
@loomlike 
Done

**Review by loomlike — APPROVED** [review]
LGTM!

**Review by blrchen — APPROVED** [review]

**Review by blrchen — APPROVED** [review]

**Pull request merged**
