### PR TITLE
Move nyc_driver_demo notebook to sample directory

### PR DESCRIPTION
**Pull request by blrchen**
## Description

This PR moves nyc_driver_demo notebook to samples directory so all notebooks are orginazed under same directory.

## How was this PR tested?

Verified existing referrence path are updated.

## Does this PR introduce any user-facing changes?

- [ ] No. You can skip the rest of this section.
- [x] Yes. Make sure to clarify your proposed changes.

### CODE REVIEW

**Review by jainr — COMMENTED** [review]
LGTM

**Review by jainr — APPROVED** [review]

**Comment by blrchen** [comment]
The link check tool will pass once this PR is merged.

**Review by Yuqing-cat — APPROVED** [review]

**Comment by Yuqing-cat** [comment]
@blrchen , Shall we resolve the conflicts and merge this in for release 0.8.0?

**Comment by blrchen** [comment]
@Yuqing-cat xiaoyong told me if this one is moved, then cli users won't see any samples under default workspace. I am abandoning this one right now.

**Pull request closed without merging**
