### PR TITLE
Create feature forms

### PR DESCRIPTION
**Pull request by enya-yx**
## Description

- Support 'create features' function through UI forms. Can create both anchor features and derived features covering all of theri items.
- Pending to do some improvement based on styles, summary pages and validations.
- Staging url: https://brave-moss-045d2ce00.1.azurestaticapps.net/new-feature
- Some example screenshots:
   - firstly, choose to create anchor feature or derived feature and set their dependencies
Screen Shot 2022-09-09 at 16 43 56

Screen Shot 2022-09-09 at 16 49 47

- then, create the feature step by step
Screen Shot 2022-09-09 at 16 50 25

Screen Shot 2022-09-09 at 16 51 25
png">

- after submitting, check feature details from UI
Screen Shot 2022-09-09 at 16 55 50

## Does this PR introduce any user-facing changes?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Make sure to clarify your proposed changes.

### CODE REVIEW

**Comment by xiaoyongzhu** [comment]
@enya-yx maybe you can paste a few screenshots of those forms/UIs?

**Comment by enya-yx** [comment]
> @enya-yx maybe you can paste a few screenshots of those forms/UIs?

Added some screenshots as references. Thanks for the suggestion.

**Comment by blrchen** [comment]
Thanks @enya-yx for the PR. I deployed a staging at https://brave-moss-045d2ce00.1.azurestaticapps.net/new-feature

Two quick questions
- Project currently is a drop down list. In a new deployment, the project list will be empty, how can use start in this case?
- As per [this](https://github.com/feathr-ai/feathr/issues/675), your UI might not work with purview, could you double check?

**Comment by enya-yx** [comment]
> Thanks @enya-yx for the PR. I deployed a staging at https://brave-moss-045d2ce00.1.azurestaticapps.net/new-feature
> 
> Two quick questions
> 
> * Project currently is a drop down list. In a new deployment, the project list will be empty, how can use start in this case?
> * As per [this](https://github.com/feathr-ai/feathr/issues/675), your UI might not work with purview, could you double check?

- My understanding is we need create features on existing projects. If that's not the case, may also need to build create project, anchors, sources forms.
- Tested by SQL and purview, both are Okay.

**Comment by blrchen** [comment]
> * My understanding is we need create features on existing projects. If that's not the case, may also need to build create project, anchors, sources forms.
> * Tested by SQL and purview, both are Okay.

For new deployment, there is no existing projects. If current UI can work with both sql and purview, then we can start review with LI, LI is using a different registry backend than purview and sql.

**Comment by Yuqing-cat** [comment]
Some feedbacks:
- Qualified name is not an input, it's auto generated by registry backend. 
- Dimension Type constraint is wrong. (combination is too flexible now.)
- May need create project outside of create feature.

**Comment by xiaoyongzhu** [comment]
Close this PR as it is stale for a while. Let me know if anyone wants to reopen it.

**Comment by xiaoyongzhu** [comment]
This function should be in by another PR.

**Pull request closed without merging**
