### PR TITLE
Fix icons in UI cannot auto scale (#737)

### LINKED ISSUE #737: [BUG] Icons in UI cannot auto scale
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### Feathr version

latest

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 20.0)**:
- **Python version**:
- **Spark version, if reporting runtime issue**:

### Describe the problem

Icons looks strange when window size changes:
image

### Tracking information

_No response_

### Code to reproduce bug

_No response_

### What component(s) does this bug affect?

- [ ] `Python Client`: This is the client users use to interact with most of our API. Mostly written in Python.
- [ ] `Computation Engine`: The computation engine that execute the actual feature join and generation work. Mostly in Scala and Spark.
- [ ] `Feature Registry API`: The frontend API layer supports SQL, Purview(Atlas) as storage. The API layer is in Python(FAST API)
- [X] `Feature Registry Web UI`: The Web UI for feature registry. Written in React

### PR DESCRIPTION
**Pull request by Fendoe**
## Description

Resolves #737 

## Does this PR introduce any user-facing changes?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Make sure to clarify your proposed changes.

### CODE REVIEW

**Comment by Yuqing-cat** [comment]
@Fendoe , Thanks for the contribution. Could you please also add the screenshot before and after your change, or provide a test web app link?

**Comment by Fendoe** [comment]
> @Fendoe , Thanks for the contribution. Could you please also add the screenshot before and after your change, or provide a test web app link?

## Before

### Screen  2000px
before screen  2000px

### Screen  1600px
before screen  1600px

### Screen  1200px
before screen  1200px

### Screen 992px
before screen 992px

### Screen 768px
before screen 768px

### Screen 576px
before screen 576px

## After

### Screen  2000px
after screen  2000px

### Screen  1600px
after screen 1600px

### Screen  1200px
after screen 1200px

### Screen 992px
after screen 992px

### Screen 768px
after screen 768px

### Screen 576px
after screen 576px

**Review by Yuqing-cat — APPROVED** [review]
LGTM.

**Review by jainr — APPROVED** [review]
Thanks for adding the before and after images, looks good.

**Pull request merged**
